# ETT Time Series Regression Hyperparameter Search (Scoped Format)
# For multivariate time series forecasting

model_name: "enhanced_tfn_regressor"

# Static configuration (applied to all trials)
data:
  dataset_name: "ett"
  csv_path: "data/ETTh1.csv"
  input_len: 96
  output_len: 24
  normalization_strategy: "global"

training:
  epochs: 30
  patience: 5
  batch_size: 32
  warmup_epochs: 2
  grad_clip: 1.0

# Hyperparameter search space definition (NEW SCOPED FORMAT)
search_space:
  # Models to search over
  models: ["enhanced_tfn_regressor", "tfn_regressor"]
  
  # Parameter sweep definitions with explicit scoping
  params:
    # Model architecture parameters
    model:
      embed_dim: [128, 256, 512]
      num_layers: 
        range: [1, 4]
        steps: 4
      kernel_type: ["rbf", "film_learnable", "compact"]
      evolution_type: ["diffusion", "cnn", "wave"]
      interference_type: ["standard", "causal"]
      dropout: [0.1, 0.2, 0.3]
      grid_size: [64, 128, 256]
    
    # Training parameters
    training:
      lr:
        # Logarithmic space from 0.0001 to 0.01 with 6 steps
        logspace: [0.0001, 0.01]
        steps: 6
      weight_decay: [0.0, 0.001, 0.01]
      batch_size: [16, 32, 64]

# Search configuration
patience: 5
min_epochs: 3
seed: 42
output_dir: "./search_results/ett_regression_scoped" 