# ETT Time Series Regression Hyperparameter Search
# Comprehensive search for time series forecasting

model_name: "enhanced_tfn_regressor"  # Default model (can be overridden in search_space)

# Static configuration (applied to all trials)
data:
  dataset_name: "ett"
  csv_path: "data/ETTh1.csv"
  input_len: 96
  output_len: 24
  normalization_strategy: "global"

training:
  epochs: 30
  patience: 5
  batch_size: 64
  warmup_epochs: 2
  grad_clip: 1.0

# Hyperparameter search space definition
search_space:
  # Models to search over
  models: ["enhanced_tfn_regressor", "tfn_regressor"]
  
  # Parameter sweep definitions
  params:
    # Model architecture parameters
    model.embed_dim:
      values: [128, 256, 512]
    
    model.num_layers:
      values: [2, 4, 6]
    
    model.kernel_type:
      values: ["rbf", "compact", "fourier"]
    
    model.evolution_type:
      values: ["cnn", "diffusion", "modernized_cnn"]
    
    model.grid_size:
      values: [64, 128, 256]
    
    # Advanced parameter definitions
    training.lr:
      # Logarithmic space from 0.0001 to 0.01 with 5 steps
      logspace: [0.0001, 0.01]
      steps: 5
    
    training.weight_decay:
      values: [0.0, 0.01, 0.001]
    
    model.dropout:
      # Linear range from 0.1 to 0.3 with 3 steps
      range: [0.1, 0.3]
      steps: 3

# Search configuration
patience: 5
min_epochs: 3
seed: 42
output_dir: "./search_results/ett_regression" 