# Minimal Hyperparameter Search Example
# Perfect for quick testing and validation

model_name: "tfn_classifier"

# Static configuration (applied to all trials)
data:
  dataset_name: "synthetic"
  seq_len: 10
  dataset_size: 100

training:
  epochs: 5
  batch_size: 16
  patience: 2
  min_epochs: 2

# Hyperparameter search space definition
search_space:
  # Models to search over
  models: ["tfn_classifier"]
  
  # Parameter sweep definitions
  params:
    # Simple discrete values
    model.embed_dim:
      values: [64, 128]
    
    model.kernel_type:
      values: ["rbf", "compact"]
    
    model.num_layers:
      values: [2, 3]
    
    # Training parameter
    training.lr:
      values: [0.001, 0.005]

# Search configuration
patience: 2
min_epochs: 2
seed: 42
output_dir: "./search_results/minimal" 