data:
  dataset_name: arxiv
  file_path: data/arxiv_sample.csv
  tokenizer_name: bert-base-uncased
  max_length: 256
  text_col: abstract
  label_col: category
model:
  vocab_size: 30522
  embed_dim: 128
  num_classes: 10
  num_layers: 4
  dropout: 0.2
training:
  batch_size: 32
  lr: 2e-5
  epochs: 5
  grad_clip: 1.0
  log_interval: 20 