model_name: tfn_regressor
task: time_series
data:
  dataset_name: ett
  csv_path: /kaggle/input/training/MyDrive/training/ETT-small/ETTh1.csv
  input_len: 336
  output_len: 96
model:
  input_dim: 7
  embed_dim: 256
  output_dim: 1
  output_len: 96
  num_layers: 4
  dropout: 0.2
  kernel_type: rbf
  evolution_type: cnn
training:
  batch_size: 64
  lr: 1e-4
  epochs: 20
  warmup_epochs: 2
  grad_clip: 1.0
  log_interval: 50 