# Example configuration with Weights & Biases integration
# Usage: python train.py --config configs/ett_wandb.yaml

model_name: enhanced_tfn_regressor
task: time_series

data:
  dataset_name: ett
  csv_path: data/ETTh1.csv
  input_len: 96
  output_len: 24
  input_dim: 7
  output_dim: 1

model:
  input_dim: 7
  embed_dim: 256
  output_dim: 1
  output_len: 24
  num_layers: 4
  dropout: 0.2
  kernel_type: rbf
  interference_type: standard

training:
  batch_size: 64
  lr: 1e-4
  epochs: 10
  warmup_epochs: 2
  grad_clip: 1.0
  log_interval: 50
  weight_decay: 0.0

# Weights & Biases Configuration
wandb:
  use_wandb: true
  project_name: "tfn-time-series"
  experiment_name: "ett-forecasting-v1"
  # Additional wandb settings can be added here
  # tags: ["time-series", "forecasting", "tfn"]
  # notes: "Experiment with ETT dataset using enhanced TFN"
  # group: "baseline-experiments" 