data:
  dataset: "ett"
  csv_path: "data/ETTh1.csv"
  input_len: 96
  output_len: 24
  normalization_strategy: "global"
  instance_normalize: false

model:
  task: "regression"
  input_dim: 7  # Number of features in ETT dataset
  output_dim: 1
  output_len: 24
  embed_dim: 128
  num_layers: 2
  kernel_type: "rbf"
  evolution_type: "cnn"
  grid_size: 100
  time_steps: 3
  dropout: 0.1
  positional_embedding_strategy: "time_based"
  calendar_features: ["hour", "day_of_week", "day_of_month", "month", "is_weekend"]
  feature_cardinalities:
    hour: 24
    day_of_week: 7
    day_of_month: 31
    month: 12
    is_weekend: 2

training:
  batch_size: 32
  lr: 1e-3
  epochs: 50
  weight_decay: 1e-4
  optimizer: "adamw"
  warmup_epochs: 5
  grad_clip: 1.0
  log_interval: 100 