data:
  dataset_name: glue
  # Kaggle dataset file (the basename is enough; resolver searches /kaggle/input/**)
  file_path: multinli_train.tsv
  tokenizer_name: bert-base-uncased
  max_length: 128
  # MNLI files use 'premise' column for a single-sentence representation
  text_col: premise
  label_col: label
model:
  vocab_size: 30522
  embed_dim: 128
  num_classes: 2
  num_layers: 4
  dropout: 0.2
training:
  batch_size: 32
  lr: 2e-5
  epochs: 5
  grad_clip: 1.0
  log_interval: 20 