data:
  dataset_name: glue
  # SST-2 train split from Google Drive
  file_path: /content/drive/MyDrive/training/SST-2/train.tsv
  tokenizer_name: bert-base-uncased
  max_length: 128
  text_col: sentence
  label_col: label
model:
  vocab_size: 30522
  embed_dim: 128
  num_classes: 2
  num_layers: 4
  dropout: 0.2
training:
  batch_size: 32
  lr: 2e-5
  epochs: 5
  grad_clip: 1.0
  log_interval: 20 