model_name: tfn_classifier
data:
  dataset_name: imdb
  file_path: /kaggle/input/training/training/IMDB/IMDB Dataset.csv
  tokenizer_name: bert-base-uncased
  max_length: 512
  text_col: review
  label_col: sentiment  # For classification
  regression_col: sentiment  # For regression
  split_frac: {"train": 0.8, "val": 0.1, "test": 0.1}  # Proper train/val/test split

model:
  vocab_size: 30522
  embed_dim: 128
  num_classes: 2  # positive/negative sentiment
  num_layers: 4
  dropout: 0.2
  kernel_type: rbf
  evolution_type: cnn

training:
  batch_size: 32
  lr: 1e-3
  epochs: 5
  warmup_epochs: 3
  grad_clip: 1.0
  log_interval: 10 