model_name: tfn_classifier
data:
  dataset_name: imdb
  file_path: /content/drive/MyDrive/training/IMDB/IMDB Dataset.csv
  tokenizer_name: bert-base-uncased
  max_length: 256
  text_col: review
  label_col: sentiment  # For classification
  regression_col: sentiment  # For regression

model:
  vocab_size: 30522
  embed_dim: 128
  num_classes: 2  # positive/negative sentiment
  num_layers: 4
  dropout: 0.2
  kernel_type: rbf
  evolution_type: cnn

training:
  batch_size: 32
  lr: 1e-3
  epochs: 5
  grad_clip: 1.0
  log_interval: 10 