# This is a temporary config file created and run from the notebook.
data:
  dataset_name: "ett"
  csv_path: "data/ETTh1.csv"  # Use local file instead of Google Drive path
  input_len: 336
  output_len: 96

# Explicitly define all required model parameters not in the sweep
model:
  input_dim: 7
  output_dim: 1
  output_len: 96  # Copy from data section for model
  kernel_type: "film_learnable"
  interference_type: "causal"
  grid_size: 128  # Add missing parameter
  num_layers: 1   # Add missing parameter

training:
  epochs: 20
  batch_size: 64
  patience: 3
  min_epochs: 5
  warmup_epochs: 5

search_space:
  models: ["enhanced_tfn_regressor"]
  
  params:
    model:
      embed_dim: [64]  # Reduced for testing
      evolution_type: ["cnn"]  # Reduced for testing
      grid_size: [64]  # Reduced for testing
      num_layers: [1]  # Reduced for testing
    training:
      lr: [1e-4]  # Reduced for testing 