model_name: tfn_regressor
task: regression
strategy: pde
data:
  dataset_name: pde
  file_path: data/pde_data.mat
  initial_condition_key: a
  solution_key: u
  grid_key: x
  input_timesteps: 1
  target_timestep: 10
  normalize: true
  normalization_strategy: global
model:
  input_dim: 1
  embed_dim: 256
  output_dim: 1
  num_layers: 4
  dropout: 0.1
  kernel_type: rbf
  evolution_type: cnn
training:
  batch_size: 32
  lr: 1e-4
  epochs: 100
  warmup_epochs: 10
  grad_clip: 1.0
  log_interval: 50 