data:
  dataset_name: pg19
  base_path: /kaggle/input/the-pg19-language-modeling-benchmark-dataset
  tokenizer_name: gpt2
  max_length: 512
  text_col: text
model:
  vocab_size: 50257
  embed_dim: 256
  num_layers: 8
  dropout: 0.2
training:
  batch_size: 8
  lr: 5e-5
  epochs: 5
  grad_clip: 1.0
  log_interval: 20 