model_name: tfn_regressor
data:
  dataset_name: stock
  csv_path: /content/drive/MyDrive/training/sandp500/sp500_stocks.csv
  input_len: 120
  output_len: 20
  target_col: "Close"
  ticker: null
model:
  input_dim: 5
  embed_dim: 128
  output_dim: 1
  output_len: 20
  num_layers: 4
  dropout: 0.2
  kernel_type: rbf
  evolution_type: cnn
training:
  batch_size: 64
  lr: 1e-4
  epochs: 20
  grad_clip: 1.0
  log_interval: 50 