data:
  seq_len: 50
  dataset_size: 10000
  pad_idx: 0
model:
  vocab_size: 20
  embed_dim: 128
  grid_size: 256
  kernel_type: "rbf"
  evolution_type: "cnn"
  time_steps: 3
  dropout: 0.1
training:
  batch_size: 64
  lr: 1e-3
  epochs: 10
  grad_clip: 1.0
  log_interval: 100 