# Example configuration for synthetic datasets
# This demonstrates the new pattern where file_path must be specified in config
# rather than being hardcoded in the registry

# Heat Equation Dataset Example
heat_equation:
  data:
    dataset_name: heat_equation
    file_path: data/synthetic/heat_equation.pt  # Required - no longer hardcoded
    split_ratios:  # Optional - has defaults
      train: 0.8
      val: 0.1
      test: 0.1
    seed: 42  # Optional - has defaults
  
  model:
    model_name: tfn_regressor  # Compatible with regression tasks
    embed_dim: 64
    output_dim: 1
    output_len: 100
  
  training:
    batch_size: 32
    lr: 1e-3
    epochs: 100

# Delayed Copy Dataset Example
delayed_copy:
  data:
    dataset_name: delayed_copy
    file_path: data/synthetic/delayed_copy.pt  # Required - no longer hardcoded
    split_ratios:  # Optional - has defaults
      train: 0.8
      val: 0.1
      test: 0.1
    seed: 42  # Optional - has defaults
  
  model:
    model_name: tfn_language_model  # Compatible with language_modeling tasks
    vocab_size: 11  # From dataset metadata
    embed_dim: 128
    seq_len: 10000
  
  training:
    batch_size: 16
    lr: 1e-3
    epochs: 50

# Irregular Sampling Dataset Example
irregular_sampling:
  data:
    dataset_name: irregular_sampling
    file_path: data/synthetic/irregular_sampling.pt  # Required - no longer hardcoded
    split_ratios:  # Optional - has defaults
      train: 0.8
      val: 0.1
      test: 0.1
    seed: 42  # Optional - has defaults
  
  model:
    model_name: tfn_regressor  # Compatible with regression tasks
    embed_dim: 64
    output_dim: 1
    output_len: 200
  
  training:
    batch_size: 32
    lr: 1e-3
    epochs: 100

# Key Changes Made:
# 1. file_path is now REQUIRED in config files (moved from registry defaults)
# 2. split_ratios and seed remain OPTIONAL (kept in registry defaults)
# 3. This enforces the resolve_data_path pattern for consistency
# 4. Config files now explicitly specify data locations
# 5. No more hardcoded paths in the registry 